# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Inst\file1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(389, 147)
        Dialog.setMinimumSize(QtCore.QSize(389, 147))
        Dialog.setMaximumSize(QtCore.QSize(389, 147))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        Dialog.setAcceptDrops(False)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: #f199ff;")
        Dialog.setSizeGripEnabled(True)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 80, 191, 21))
        self.progressBar.setStyleSheet("background-color: #ec6eff;")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 291, 20))
        self.lineEdit.setStyleSheet("color: #0d0d0d;\n"
"font: 8pt \"Segoe UI Symbol\";\n"
"background-color: #ec6eff;\n"
"border: None;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 47, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 50, 291, 20))
        self.lineEdit_2.setStyleSheet("color: #0d0d0d;\n"
"font: 8pt \"Segoe UI Symbol\";\n"
"background-color: #ec6eff;\n"
"border: None;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 47, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 90, 111, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: #0d0d0d;\n"
"    font: 8pt \"Segoe UI Symbol\";\n"
"    background-color: #ec6eff;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.progressBar_2 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 110, 191, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 0, 321, 20))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "url1"))
        self.label_2.setText(_translate("Dialog", "url2"))
        self.pushButton.setText(_translate("Dialog", "Start"))
        self.label_3.setText(_translate("Dialog", "Если программа не отвечает, значит она парсит фоловеров"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
